apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-longhorn-certs
  namespace: longhorn-system
spec:
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: tls-longhorn-certs
  dnsNames:
  - longhorn.$DOMAIN