apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: zack.brady@ranchergovernment.com
    privateKeySecretRef:
      name: letsencrypt-prododuction
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx