apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher-ingress
  namespace: cattle-system
spec:
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: tls-rancher-certs
  dnsNames:
  - rancher.$DOMAIN