apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    harvesterhci.io/cloud-init-template: user
  name: cloud-init-user-data
  namespace: default
data:
  cloudInit: |-
    #cloud-config
    #simple cloud-init user-data
    #reach out with questions to @zackbradys

    package_update: true
    packages:
      - qemu-guest-agent
      - sudo
      - wget
      - tree
      - vim
    package_upgrade: false
    runcmd:
      - - systemctl
        - enable
        - --now
        - qemu-guest-agent.service
    users:
      - name: root
        hashed_passwd: $6$fgls6Nv/5eS$iozPi2/3f9SE7cR5mvTlriGkRZRSuhzFs0s6fVWzUXiL19E27hVgAo3mZwCdzlDsiUq1YRJeyPtql6FkPhMZP0
        lock_passwd: false
        shell: /bin/bash
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcZuBmnPjv180et6/RgsO+KaME63y+b69bw7K/jXdQ5D9m9EoH9rhqVLOy1Mp2PSF9xWrqwMM2a3/o4SJz78CkxNl2EtyVo9+gqV3ULimF0phe9u8gH9HSnfLFUuqH3+hBfvfuk1Ve+/4BPafW43ureKDJzL5Z9usf5bA2K0fQndSfdZAi5xEb8Jd7QtydLy8Btj7tn5H5FJ42c+tzvUSUY2lDnN/MwgoHqMZxYD+tptGM15oYAxfb1MjHZhVJS1/zwFfrE+rgECbOLAYUIYilNNAMTzHgz2BN9DfXxzuIeJwxaGQbU7fcfODqWlEUgkJrw9U70eAplAik2H0APkCktLVNZK7d5ky/lt13nmWW7gUup5OjLjZtXrKO3ZrKjmRg7mL0ZVocp/zhbkukUbxT8hdnDfHPTN+PaD4VpL35AnvjO3UrmLALVEjyZ63eTwujH5p+t0QJsdpqNAtKbPiw0G4EkBW9SNTUu+tkSgjrub+bHp/lSdPiXkc3etHn/M2v81l560etrdXVuI36Lnyogv2ZYhN6QeODDWq0NJD/Jm8oPuQkNPfAcLnrUHPZXe9xl5ztGDpz6HVdvnoI8yO9lVEn/gw6hKFoEdz6zy5gniZoC+N2C67y+D5s6m6RrmISLYvROoSzOWOU3OrHR68tOuidyFYQUlEGy7WL59qiJQ== zackbradys@Zacks-MBP
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDF6mDaZKkzx6At5mkCxozEIcS00Y8ph+ax8incUgtkcWXMLutspn5NpDLmZRz0DUlViHNUKYhDtrhGOo38xjREztFxVHGFbtbk5KYs/doBsqmrFTEFJoGKpdQFZE/NzDA0h7YZDsoV8xwXphUHaR5fBNDK6YQ0yR72R689vn9WtZoYTUdv6qMvotvji564bwbPStU0P2BkFC9syCwJMIrTHcI6Yt518Tdm6D2deGWtAyEAJ8nR1eVLiUczwgix4oWBE016bCwl6wOgoXoGY7gfy147jM2vQGdMGHgZaJqy5R6cvPI5WxEG8EbtgmPy988ZBTMXWKLFOG7ujYWPQ3zPeRiPkxRM6ZRxwfZoJ2V4vGx4howwmEuvnuO1NRcW7qmsCgmkULfaLhVyYGzkctpKCPlioAA465hBQL8eYOpf7hosblMEG46jPp6P1pNeo3iKHLmwmxv6ceNjwWBMw+lXIOD7iaq5FOFdj1kMD+IFjFL50zuWdrVZqSV3i4VPs1xl3t6dJyVMrGsmIzFfpAhxfzpMETMAAAbG6ze30cwmnWychEFQcUKWanfp5IzmDa5ywy1tdZ09d5L7731UByq8VDf9zYy8hId0a4ATH4r2fhzonyA2rgSuE8o4AG83rMb8qAA1/77if5RuOw6Uxn6cFGkZZnyZyvFFI39flqd/6Q== zackbradys@Zacks-Work-MBP
