apiVersion: v1
kind: Secret
metadata:
  name: test-volume
  namespace: default
stringData:
  CRYPTO_KEY_VALUE: "LonghornEncryptedPa22word"
  CRYPTO_KEY_PROVIDER: "secret"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-volume
  namespace: default
spec:
  storageClassName: "longhorn-encrypted-per-volume"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi